config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # dá para tirar only, e apenas deixar resources :articles
end


# resources :nome que dá todas as rotas para articles, mas como apenas queremos algumas, definimos
# com only[:ações e rotas que queremos aqui]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articles.rb
class Articles < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/course.rb
class Course < ApplicationRecord
    # está herdando dessa mesma pasta, de application_record.rb
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]    
    
    def index
        @articles = Articles.all
    end

    def show
        # @article = Articles.find(params[:id])
        # para que essa varíavel fique disponível global, @ para torná-la uma 
        # instance variable
    end

    def new
        # necessário iniciar instância de @article aqui, para que em create, no if no template
        # não gere erro ao carregar a página, por nenhum @article ter sido editado ainda
        @articles = Articles.new
    end


    # por algum motivo, def edit vem antes de def create
    def edit 
       # @article = Articles.find(params[:id])
    end

    def update
        # @article = Articles.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = 'Article was updated successfully.'
            redirect_to @article
        else
            render 'edit'
        end
    end

    def create 

        # def create é definido automaticamente como tipo POST na página de referência 
        # na qual se encontra

        @articles = Articles.new(article_params)
        # checar diferentes resultados com
        # render plain: @article.inspect => inspect retornará objeto legível
        # render plain: @article
        if @articles.save
            # se é possível salvar por passar nas validações, redireciona
            redirect_to article_path(@articles)
            # caso sucesso, helper notice dará mensagem
            flash[:notice] = 'Article was created successfully'
            # essa mensagem é editada em layouts/application.html.erb, porque ele aparece
            # em todos os lugares. A mensagem é exibida no topo de qualquer template
        else
            render 'new'
            # caso não, renderiza a new.form de novo
        end
        # mas essa linha acima pode ser apenas:
        # redirect_to @articles

        # articles.errors.full_messages => mostra todas as mensagens de erros nas validações

        # articles.errors.full_messages.each do |msg|
        # puts msg
        # end
    end
    
    def destroy 
        # @article = Articles.find(params[:id])
        @article.destroy
        redirect_to '/articles'
    end
    
    private

    def set_article
        @article = Articles.find(params[:id])
        # ao setar esse método privado, todos os @article acima podem ser removidos, por conta 
        # do before_action
    end

    def article_params
        params.require(:articles).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
  
    def about
    end
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_commentaries.html.erb
<% # essa página se refere à antiga new.html.erb %>

<% if @articles.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @articles.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :articles, url: articles_path, local: true do |f| %>
<%# provided the model name as a symble :article%  submits para articles_path, local true 
apenas é preciso porque é ajax apenas no form_with%>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<%= link_to "Return to articles list", articles_path %>
<% end %> 

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %> 

app/views/articles/edit.html.erb
<h1>Edit article</h1>


<%= render 'form' %>

<%= link_to "Cancel and return to articles list", articles_path %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan='3'>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <td><%= link_to 'Show', article_path(article.id) %></td>
                <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
                <td><%= link_to 'Delete', article_path(article.id), method: :delete,  data: { confirm: "Are you sure?" }%></td>
            </tr>
        <% end %>
    </tbody>
</table>
<p><%= link_to 'Create a new article', new_article_path %></p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>



<% if @articles.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @articles.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :articles, url: articles_path, local: true do |f| %>
<%# provided the model name as a symble :article%  submits para articles_path, local true 
apenas é preciso porque é ajax apenas no form_with%>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<%= link_to "Return to articles list", articles_path %>
<% end %> 

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p> 

<%= link_to 'Edit', edit_article_path(@article)%>
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Return to articles list", articles_path %>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg|%>
      <%= msg%>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% # como esse está sendo pego pelo app inteiro, é necessário identificar a pasta no body, layouts nesse caso. O que não acontece quando o arquivo está mna mesma pasta em outros lugares, como o _form de articles %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Articles listing', articles_path %>
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to the Home page</h1>

<%= link_to 'Articles listing', articles_path %>
<%= link_to 'About page', about_path %>